// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (
                   id,
                   user_id,
                   name,
                   encrypted_number,
                   encrypted_expired_date,
                   expired_card_holder_name,
                   encrypted_cvv,
                   encrypted_notes
)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
       )
RETURNING id, user_id, name, encrypted_number, encrypted_expired_date, expired_card_holder_name, encrypted_cvv, encrypted_notes, deleted_at, updated_at, created_at
`

type CreateCardParams struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	Name                  string
	EncryptedNumber       []byte
	EncryptedExpiredDate  []byte
	ExpiredCardHolderName []byte
	EncryptedCvv          []byte
	EncryptedNotes        []byte
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.EncryptedNumber,
		arg.EncryptedExpiredDate,
		arg.ExpiredCardHolderName,
		arg.EncryptedCvv,
		arg.EncryptedNotes,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EncryptedNumber,
		&i.EncryptedExpiredDate,
		&i.ExpiredCardHolderName,
		&i.EncryptedCvv,
		&i.EncryptedNotes,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :execrows
UPDATE cards
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type DeleteCardParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCard(ctx context.Context, arg DeleteCardParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCard, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCards = `-- name: ListCards :many
SELECT id, user_id, name, encrypted_number, encrypted_expired_date, expired_card_holder_name, encrypted_cvv, encrypted_notes, deleted_at, updated_at, created_at
FROM cards
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) ListCards(ctx context.Context, userID uuid.UUID) ([]Card, error) {
	rows, err := q.db.Query(ctx, listCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.EncryptedNumber,
			&i.EncryptedExpiredDate,
			&i.ExpiredCardHolderName,
			&i.EncryptedCvv,
			&i.EncryptedNotes,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards
SET
    name = $3,
    encrypted_number = $4,
    encrypted_expired_date = $5,
    expired_card_holder_name = $6,
    encrypted_cvv = $7,
    encrypted_notes = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, name, encrypted_number, encrypted_expired_date, expired_card_holder_name, encrypted_cvv, encrypted_notes, deleted_at, updated_at, created_at
`

type UpdateCardParams struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	Name                  string
	EncryptedNumber       []byte
	EncryptedExpiredDate  []byte
	ExpiredCardHolderName []byte
	EncryptedCvv          []byte
	EncryptedNotes        []byte
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.EncryptedNumber,
		arg.EncryptedExpiredDate,
		arg.ExpiredCardHolderName,
		arg.EncryptedCvv,
		arg.EncryptedNotes,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EncryptedNumber,
		&i.EncryptedExpiredDate,
		&i.ExpiredCardHolderName,
		&i.EncryptedCvv,
		&i.EncryptedNotes,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
