// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Name              string
	Encryptedlogin    []byte
	Encryptedpassword []byte
	Encryptednotes    []byte
	DeletedAt         pgtype.Timestamp
	UpdatedAt         time.Time
	CreatedAt         time.Time
	Version           int64
}
