// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Login     string
	Password  string
	Metadata  string
	DeletedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}
