// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (user_id, name, encryptedLogin, encryptedPassword, encryptedNotes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, encryptedlogin, encryptedpassword, encryptednotes, deleted_at, updated_at, created_at
`

type CreateCredentialParams struct {
	UserID            uuid.UUID
	Name              string
	Encryptedlogin    []byte
	Encryptedpassword []byte
	Encryptednotes    []byte
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.UserID,
		arg.Name,
		arg.Encryptedlogin,
		arg.Encryptedpassword,
		arg.Encryptednotes,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Encryptedlogin,
		&i.Encryptedpassword,
		&i.Encryptednotes,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :execrows
UPDATE credentials
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type DeleteCredentialParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCredential, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, user_id, name, encryptedlogin, encryptedpassword, encryptednotes, deleted_at, updated_at, created_at
FROM credentials
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) ListCredentials(ctx context.Context, userID uuid.UUID) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Encryptedlogin,
			&i.Encryptedpassword,
			&i.Encryptednotes,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :one
UPDATE credentials
SET name       = $3,
    encryptedLogin    = $4,
    encryptedPassword = $5,
    encryptedNotes    = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, name, encryptedlogin, encryptedpassword, encryptednotes, deleted_at, updated_at, created_at
`

type UpdateCredentialParams struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Name              string
	Encryptedlogin    []byte
	Encryptedpassword []byte
	Encryptednotes    []byte
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, updateCredential,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Encryptedlogin,
		arg.Encryptedpassword,
		arg.Encryptednotes,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Encryptedlogin,
		&i.Encryptedpassword,
		&i.Encryptednotes,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
