// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/domain/auth/interfaces/crypto.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/domain/auth/interfaces/crypto.go -destination=internal/server/domain/auth/interfaces/mocks/mock_crypto.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "go.uber.org/mock/gomock"
)

// MockCryptoService is a mock of CryptoService interface.
type MockCryptoService struct {
	ctrl     *gomock.Controller
	recorder *MockCryptoServiceMockRecorder
	isgomock struct{}
}

// MockCryptoServiceMockRecorder is the mock recorder for MockCryptoService.
type MockCryptoServiceMockRecorder struct {
	mock *MockCryptoService
}

// NewMockCryptoService creates a new mock instance.
func NewMockCryptoService(ctrl *gomock.Controller) *MockCryptoService {
	mock := &MockCryptoService{ctrl: ctrl}
	mock.recorder = &MockCryptoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCryptoService) EXPECT() *MockCryptoServiceMockRecorder {
	return m.recorder
}

// CompareHashAndPassword mocks base method.
func (m *MockCryptoService) CompareHashAndPassword(hashedPassword, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareHashAndPassword", hashedPassword, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompareHashAndPassword indicates an expected call of CompareHashAndPassword.
func (mr *MockCryptoServiceMockRecorder) CompareHashAndPassword(hashedPassword, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCall(mr.mock, "CompareHashAndPassword", hashedPassword, password)
}

// DeriveEncryptionKey mocks base method.
func (m *MockCryptoService) DeriveEncryptionKey(password, salt string) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeriveEncryptionKey", password, salt)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// DeriveEncryptionKey indicates an expected call of DeriveEncryptionKey.
func (mr *MockCryptoServiceMockRecorder) DeriveEncryptionKey(password, salt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCall(mr.mock, "DeriveEncryptionKey", password, salt)
}

// GenerateSalt mocks base method.
func (m *MockCryptoService) GenerateSalt() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSalt")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSalt indicates an expected call of GenerateSalt.
func (mr *MockCryptoServiceMockRecorder) GenerateSalt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCall(mr.mock, "GenerateSalt")
}

// HashPassword mocks base method.
func (m *MockCryptoService) HashPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockCryptoServiceMockRecorder) HashPassword(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCall(mr.mock, "HashPassword", password)
}
