// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	EncryptedPath  []byte
	EncryptedSize  []byte
	EncryptedNotes []byte
	UploadedAt     time.Time
}
