// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Filename   string
	FilePath   string
	FileSize   int64
	MimeType   string
	UploadedAt time.Time
}
