// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO files (id, user_id, filename, file_path, file_size, mime_type, uploaded_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateFileParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Filename   string
	FilePath   string
	FileSize   int64
	MimeType   string
	UploadedAt time.Time
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.Exec(ctx, createFile,
		arg.ID,
		arg.UserID,
		arg.Filename,
		arg.FilePath,
		arg.FileSize,
		arg.MimeType,
		arg.UploadedAt,
	)
	return err
}

const deleteFile = `-- name: DeleteFile :execrows
DELETE
FROM files
WHERE id = $1
  AND user_id = $2
`

type DeleteFileParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFile, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFiles = `-- name: ListFiles :many
SELECT id, user_id, filename, file_path, file_size, mime_type, uploaded_at
FROM files
WHERE user_id = $1
ORDER BY uploaded_at DESC
`

func (q *Queries) ListFiles(ctx context.Context, userID uuid.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listFiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
