// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (id, user_id, name, encrypted_path, encrypted_size, encrypted_notes, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, encrypted_path, encrypted_size, encrypted_notes, deleted_at, updated_at, created_at, version
`

type CreateFileParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	EncryptedPath  []byte
	EncryptedSize  []byte
	EncryptedNotes []byte
	UpdatedAt      time.Time
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.EncryptedPath,
		arg.EncryptedSize,
		arg.EncryptedNotes,
		arg.UpdatedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EncryptedPath,
		&i.EncryptedSize,
		&i.EncryptedNotes,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :execrows
DELETE
FROM files
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type DeleteFileParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFile, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFile = `-- name: GetFile :one
SELECT id, user_id, name, encrypted_path, encrypted_size, encrypted_notes, deleted_at, updated_at, created_at, version
FROM files
WHERE id = $1 AND
    user_id = $2 AND
    deleted_at IS NULL
`

type GetFileParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (File, error) {
	row := q.db.QueryRow(ctx, getFile, arg.ID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EncryptedPath,
		&i.EncryptedSize,
		&i.EncryptedNotes,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const getFileForUpdate = `-- name: GetFileForUpdate :one
SELECT id, user_id, name, encrypted_path, encrypted_size, encrypted_notes, deleted_at, updated_at, created_at, version
FROM files
WHERE id = $1
  AND user_id = $2
FOR UPDATE
`

type GetFileForUpdateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetFileForUpdate(ctx context.Context, arg GetFileForUpdateParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileForUpdate, arg.ID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EncryptedPath,
		&i.EncryptedSize,
		&i.EncryptedNotes,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const listFiles = `-- name: ListFiles :many
SELECT id, user_id, name, encrypted_path, encrypted_size, encrypted_notes, deleted_at, updated_at, created_at, version
FROM files
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListFiles(ctx context.Context, userID uuid.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listFiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.EncryptedPath,
			&i.EncryptedSize,
			&i.EncryptedNotes,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFile = `-- name: UpdateFile :one
UPDATE files
SET
    name = $3,
    encrypted_path = $4,
    encrypted_size = $5,
    encrypted_notes = $6,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND
    user_id = $2 AND
    deleted_at IS NULL
RETURNING id, user_id, name, encrypted_path, encrypted_size, encrypted_notes, deleted_at, updated_at, created_at, version
`

type UpdateFileParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	EncryptedPath  []byte
	EncryptedSize  []byte
	EncryptedNotes []byte
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, updateFile,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.EncryptedPath,
		arg.EncryptedSize,
		arg.EncryptedNotes,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EncryptedPath,
		&i.EncryptedSize,
		&i.EncryptedNotes,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}
