// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/domain/credential/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/client/domain/credential/interfaces.go -destination=internal/client/domain/credential/mock_client_test.go -package=credential
//

// Package credential is a generated GoMock package.
package credential

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCredentialClient is a mock of CredentialClient interface.
type MockCredentialClient struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialClientMockRecorder
	isgomock struct{}
}

// MockCredentialClientMockRecorder is the mock recorder for MockCredentialClient.
type MockCredentialClientMockRecorder struct {
	mock *MockCredentialClient
}

// NewMockCredentialClient creates a new mock instance.
func NewMockCredentialClient(ctrl *gomock.Controller) *MockCredentialClient {
	mock := &MockCredentialClient{ctrl: ctrl}
	mock.recorder = &MockCredentialClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialClient) EXPECT() *MockCredentialClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCredentialClient) Create(ctx context.Context, creds Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, creds)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCredentialClientMockRecorder) Create(ctx, creds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCredentialClient)(nil).Create), ctx, creds)
}

// Delete mocks base method.
func (m *MockCredentialClient) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCredentialClientMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCredentialClient)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockCredentialClient) List(ctx context.Context) ([]Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCredentialClientMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCredentialClient)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockCredentialClient) Update(ctx context.Context, id string, creds Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, creds)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCredentialClientMockRecorder) Update(ctx, id, creds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCredentialClient)(nil).Update), ctx, id, creds)
}
