// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/domain/secret/credential/interfaces/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/domain/secret/credential/interfaces/repository.go -destination=internal/server/domain/secret/credential/interfaces/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	interfaces "github.com/aifedorov/gophkeeper/internal/server/domain/secret/credential/interfaces"
	"github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateCredential mocks base method.
func (m *MockRepository) CreateCredential(ctx context.Context, userID uuid.UUID, credential interfaces.RepositoryCredential) (*interfaces.RepositoryCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredential", ctx, userID, credential)
	ret0, _ := ret[0].(*interfaces.RepositoryCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCredential indicates an expected call of CreateCredential.
func (mr *MockRepositoryMockRecorder) CreateCredential(ctx, userID, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCall(mr.mock, "CreateCredential", ctx, userID, credential)
}

// DeleteCredential mocks base method.
func (m *MockRepository) DeleteCredential(ctx context.Context, userID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredential", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCredential indicates an expected call of DeleteCredential.
func (mr *MockRepositoryMockRecorder) DeleteCredential(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCall(mr.mock, "DeleteCredential", ctx, userID, id)
}

// GetCredential mocks base method.
func (m *MockRepository) GetCredential(ctx context.Context, userID, id uuid.UUID) (*interfaces.RepositoryCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredential", ctx, userID, id)
	ret0, _ := ret[0].(*interfaces.RepositoryCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredential indicates an expected call of GetCredential.
func (mr *MockRepositoryMockRecorder) GetCredential(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCall(mr.mock, "GetCredential", ctx, userID, id)
}

// ListCredentials mocks base method.
func (m *MockRepository) ListCredentials(ctx context.Context, userID uuid.UUID) ([]interfaces.RepositoryCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCredentials", ctx, userID)
	ret0, _ := ret[0].([]interfaces.RepositoryCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCredentials indicates an expected call of ListCredentials.
func (mr *MockRepositoryMockRecorder) ListCredentials(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCall(mr.mock, "ListCredentials", ctx, userID)
}

// UpdateCredential mocks base method.
func (m *MockRepository) UpdateCredential(ctx context.Context, userID uuid.UUID, credential interfaces.RepositoryCredential) (*interfaces.RepositoryCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredential", ctx, userID, credential)
	ret0, _ := ret[0].(*interfaces.RepositoryCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCredential indicates an expected call of UpdateCredential.
func (mr *MockRepositoryMockRecorder) UpdateCredential(ctx, userID, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCall(mr.mock, "UpdateCredential", ctx, userID, credential)
}
