// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/server/api/grpc/proto/binary/v1/binary.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Size          *int64                 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	MimeType      *string                `protobuf:"bytes,3,opt,name=mime_type,json=mimeType" json:"mime_type,omitempty"`
	Notes         *string                `protobuf:"bytes,4,opt,name=notes" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MetadataRequest) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *MetadataRequest) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *MetadataRequest) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadRequest_File
	//	*UploadRequest_Chunk
	Data          isUploadRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDescGZIP(), []int{1}
}

func (x *UploadRequest) GetData() isUploadRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadRequest) GetFile() *MetadataRequest {
	if x != nil {
		if x, ok := x.Data.(*UploadRequest_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *UploadRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadRequest_Data interface {
	isUploadRequest_Data()
}

type UploadRequest_File struct {
	File *MetadataRequest `protobuf:"bytes,1,opt,name=file,oneof"`
}

type UploadRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,oneof"`
}

func (*UploadRequest_File) isUploadRequest_Data() {}

func (*UploadRequest_Chunk) isUploadRequest_Data() {}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        *string                `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDescGZIP(), []int{2}
}

func (x *UploadResponse) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Size          *int64                 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Notes         *string                `protobuf:"bytes,4,opt,name=notes" json:"notes,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=uploaded_at,json=uploadedAt" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDescGZIP(), []int{3}
}

func (x *MetadataResponse) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *MetadataResponse) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MetadataResponse) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *MetadataResponse) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *MetadataResponse) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDescGZIP(), []int{4}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*MetadataResponse    `protobuf:"bytes,1,rep,name=files" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetFiles() []*MetadataResponse {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_internal_server_api_grpc_proto_binary_v1_binary_proto protoreflect.FileDescriptor

const file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDesc = "" +
	"\n" +
	"5internal/server/api/grpc/proto/binary/v1/binary.proto\x12\tbinary.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"l\n" +
	"\x0fMetadataRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"a\n" +
	"\rUploadRequest\x120\n" +
	"\x04file\x18\x01 \x01(\v2\x1a.binary.v1.MetadataRequestH\x00R\x04file\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\")\n" +
	"\x0eUploadResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\x9d\x01\n" +
	"\x10MetadataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\x12;\n" +
	"\vuploaded_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\"\r\n" +
	"\vListRequest\"A\n" +
	"\fListResponse\x121\n" +
	"\x05files\x18\x01 \x03(\v2\x1b.binary.v1.MetadataResponseR\x05files2\x89\x01\n" +
	"\rBinaryService\x12?\n" +
	"\x06Upload\x12\x18.binary.v1.UploadRequest\x1a\x19.binary.v1.UploadResponse(\x01\x127\n" +
	"\x04List\x12\x16.binary.v1.ListRequest\x1a\x17.binary.v1.ListResponseB$Z\"github.com/aifedorov/gen/binary/v1b\beditionsp\xe8\a"

var (
	file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDescOnce sync.Once
	file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDescData []byte
)

func file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDescGZIP() []byte {
	file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDescOnce.Do(func() {
		file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDesc), len(file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDesc)))
	})
	return file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDescData
}

var file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_server_api_grpc_proto_binary_v1_binary_proto_goTypes = []any{
	(*MetadataRequest)(nil),       // 0: binary.v1.MetadataRequest
	(*UploadRequest)(nil),         // 1: binary.v1.UploadRequest
	(*UploadResponse)(nil),        // 2: binary.v1.UploadResponse
	(*MetadataResponse)(nil),      // 3: binary.v1.MetadataResponse
	(*ListRequest)(nil),           // 4: binary.v1.ListRequest
	(*ListResponse)(nil),          // 5: binary.v1.ListResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_internal_server_api_grpc_proto_binary_v1_binary_proto_depIdxs = []int32{
	0, // 0: binary.v1.UploadRequest.file:type_name -> binary.v1.MetadataRequest
	6, // 1: binary.v1.MetadataResponse.uploaded_at:type_name -> google.protobuf.Timestamp
	3, // 2: binary.v1.ListResponse.files:type_name -> binary.v1.MetadataResponse
	1, // 3: binary.v1.BinaryService.Upload:input_type -> binary.v1.UploadRequest
	4, // 4: binary.v1.BinaryService.List:input_type -> binary.v1.ListRequest
	2, // 5: binary.v1.BinaryService.Upload:output_type -> binary.v1.UploadResponse
	5, // 6: binary.v1.BinaryService.List:output_type -> binary.v1.ListResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_server_api_grpc_proto_binary_v1_binary_proto_init() }
func file_internal_server_api_grpc_proto_binary_v1_binary_proto_init() {
	if File_internal_server_api_grpc_proto_binary_v1_binary_proto != nil {
		return
	}
	file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes[1].OneofWrappers = []any{
		(*UploadRequest_File)(nil),
		(*UploadRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDesc), len(file_internal_server_api_grpc_proto_binary_v1_binary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_server_api_grpc_proto_binary_v1_binary_proto_goTypes,
		DependencyIndexes: file_internal_server_api_grpc_proto_binary_v1_binary_proto_depIdxs,
		MessageInfos:      file_internal_server_api_grpc_proto_binary_v1_binary_proto_msgTypes,
	}.Build()
	File_internal_server_api_grpc_proto_binary_v1_binary_proto = out.File
	file_internal_server_api_grpc_proto_binary_v1_binary_proto_goTypes = nil
	file_internal_server_api_grpc_proto_binary_v1_binary_proto_depIdxs = nil
}
